version: '3.1'

networks:
  kafka:
    external: true

services:
  mysql:
    container_name: mysql-1
    image: debezium/example-mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
    networks:
      - kafka

  connect_source:
    container_name: debezium-1
    image: debezium/connect:latest
    ports:
      - 8083:8083
    links:
      - mysql
    environment:
      - BOOTSTRAP_SERVERS=kafka-1:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    networks:
      - kafka